BOOK:
  TITLE:
    - "&5OutCraft Tutorial"
  AUTHOR:
    - "&dOutCraft Administration"
  PAGES:
    - This is the first page of the tutorial
    - The second page goes here

GUI:
  TITLE:
    - "&5OutCraft Tutorial"

WELCOME:
  MESSAGE:
    - "&5Welcome {player} to the server"